# Generated by Django 3.1.2 on 2023-01-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='用户名')),
                ('account_pwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('real_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='真实姓名')),
                ('is_delete', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='电话')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_super', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 't_account',
                'managed': True,
            },
        ),
    ]
