# Generated by Django 3.1.2 on 2023-01-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideDiagnoseModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_name', models.CharField(max_length=512, null=True, verbose_name='切片名字')),
                ('diagnose_result', models.CharField(max_length=512, null=True, verbose_name='诊断结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
            ],
            options={
                'db_table': 't_slide_diagnose_result',
                'managed': True,
            },
        ),
    ]
