# Generated by Django 3.1.2 on 2023-02-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0002_slidediagnosemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tslide',
            name='father_slide_id',
            field=models.IntegerField(default=0, verbose_name='小切片的父切片'),
        ),
    ]
