# Generated by Django 3.1.2 on 2023-02-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0003_tslide_father_slide_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tslideimage',
            name='part',
            field=models.IntegerField(null=True, verbose_name='诊断部分'),
        ),
        migrations.AddField(
            model_name='tslideimage',
            name='result',
            field=models.IntegerField(null=True, verbose_name='诊断结果'),
        ),
    ]
