# Generated by Django 3.1.2 on 2023-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0006_auto_20230302_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tslide',
            name='scanning_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='扫描时间'),
        ),
    ]
