# Generated by Django 3.1.2 on 2023-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0009_auto_20230308_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tslide',
            name='is_small_slide',
            field=models.SmallIntegerField(default=0, verbose_name='web上传的是小切片'),
        ),
    ]
