# Generated by Django 3.1.2 on 2023-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCtrl', '0010_tslide_is_small_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tslide',
            name='diagnose_time',
            field=models.DateTimeField(null=True),
        ),
    ]
